### ISSUE TITLE
Is agent.py finished?

### ISSUE THREAD

**Issue by kianyale** [ElectronicElephant/pybullet_ur5_robotiq#10]
Hi, thanks for your great work. I wonder agent.py has already finished? Is its function just to provide a heuristic template for us to refer to, and the specific functions still need to be completed by ourselves?

**Comment by ElectronicElephant** [comment]
Hi, 

The environment is in gym style so it's easy to integrate any RL algorithms. PRs are welcomed.

**Comment by Fanqyu** [comment]
I get it. Thanks a lot.

**Comment by kianyale** [comment]
I get it. Thanks a lot.
