### ISSUE TITLE
New feature request: is it possible to switch robot from ur5 to ur10 or ur3

### ISSUE THREAD

**Issue by chao0716** [ElectronicElephant/pybullet_ur5_robotiq#3]
I found it is work quite good in simulation, meanwhile, is it possible to switch robot from ur5 to ur10 or ur3

**Comment by ElectronicElephant** [comment]
Hi,

Yes, you can swith to ur3/10 very easily, as long as you get the correct URDF file, and the corresponding meshes.

The URDF files are often generated by `xacro`, which basically helps you attach a gripper to the arm. You can find these files [https://github.com/ros-industrial/universal_robot/tree/kinetic-devel/ur_description](here).
