### ISSUE TITLE
Gripper 85 bug when changing force

### ISSUE THREAD

**Issue by cyd8a18** [ElectronicElephant/pybullet_ur5_robotiq#5]
Hello,
Thank you for this model! 
I am working on an simulation where I need to modify the force in the gripper, so in the ControlGripper method that you provide, I changed the value of the force. Specifically I change the variable `desired_force` in the following parts:

1. `p.setJointMotorControl2(robotID, parent.id, controlMode, targetPosition=pose, force=desired_force, maxVelocity=parent.maxVelocity)`

2. `p.setJointMotorControl2(robotID, child.id, controlMode, targetPosition=childPose, orce=desired_force, maxVelocity=child.maxVelocity)`

I have tried different force values but I have the behavior that you can see in the image, where some of the parts of the gripper are not attached when I try to grab an object. Are there some parameter in the urdf that I must change?

![Screenshot from 2022-03-25 15-57-46](https://user-images.githubusercontent.com/70299611/160071852-b8a09d4a-c9a7-4a66-afb3-486f4781e24b.png)

**Comment by ElectronicElephant** [comment]
Hi @cyd8a18 ,

Thank you for reaching me.

It's a known issue, which we can not 100% avoid. 

First, can you confirm that you are using the code from the `robotflow` branch, instead of the `main` branch?

Second, can you tell me the value of `desired_force`?

**Comment by cyd8a18** [comment]
Thank you for your quick reply. Regarding your questions:

- I made a mistake and I was using the wrong code, I changed to `robotflow` branch
- I have tried different values for `desired_force` as 5, 25, 50.

I don't have the same behavior anymore. However, when i tried to open and close (using the same code that you have without changing the force), the gripper moves from one side to the other, as you can see in the following image:

![gripper movement open close](https://user-images.githubusercontent.com/70299611/160986384-a82b9c25-42ca-4c4f-9035-54f74613dffd.gif)

Do you have any suggestion to solve this problem?

**Comment by ElectronicElephant** [comment]
Hi @cyd8a18 ,

Sorry for the late reply. I am quite busy these days.

I think this problem may come from the non-convex objects that you add to the environment. 
Are they decomposed? (See section `V-HACD` in `https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit#`)
Can you try removing them totally?

![image](https://user-images.githubusercontent.com/20351686/163852337-ba8f53e4-3e3e-4822-ae77-7e45d2d3170f.png)
