### ISSUE TITLE
Floating base constraint

### ISSUE THREAD

**Issue by Anchoret13** [ElectronicElephant/pybullet_ur5_robotiq#6]
Hi, Thanks for your model!

I'm trying to combine ur5robotiq85 with a husky ugv. The robot itself works very well, but when I add the constraint, ugv will be attached to the robot base, and it seems like the position and orientation of the robot base is not changeable, and the base will not be affected by gravity.

I tried general methods like set useFixedBase = False when loading the URDF, but it does not work. What can I do with it?

![1](https://user-images.githubusercontent.com/22992755/167219964-41a75fdf-0ac1-4de4-bb14-527e978d37f8.png)

**Comment by ElectronicElephant** [comment]
Hi, thanks for reaching me.

Based on your description, I have a rough idea of what you are doing. Did you set the mass of the ugv? It's known that if mass=0, there will be some problems.

Anyway, I think it should work with `useFixedBase=False`. Can you show me the code?

**Comment by Anchoret13** [comment]
Hi.
I tried `useFixedBase = False` when loading the URDF files, and I'm sure the mass of ugv is correctly set.

I use createConstraint as follow:
`c = p.createConstraint(self.husky, -1,
                               self.id, -1, 
                               jointType = p.JOINT_FIXED, 
                               jointAxis = [0, 0, 0], 
                               parentFramePosition = [0, 0, 0], 
                               childFramePosition = [0., 0., -0.5],
                               childFrameOrientation = [0, 0, 0, 1])`

which husky refers to the ugv, and id refers to the ur5robotiq85.

**Comment by ElectronicElephant** [comment]
Hi @Anchoret13 

After some work, I finally know what's happening here.

In the file `urdf/ur5_robotiq_85.urdf`, there is a link named `world`, and the robot base, `base_link`, is attached onto it. You can simply comment these lines out.

Starting from Line. 538
```
<!--################################################
  ########          connect model                #####
  ####################################################-->

  <!-- <link name="world"/> -->
  <!-- connect gripper to arm -->
  <joint name="robotiq_85_base_joint" type="fixed">
    <parent link="ee_link"/>
    <child link="robotiq_arg2f_base_link"/>
    <origin rpy="0 1.57079632679 0" xyz="0 0 0"/>
  </joint>

<!--  <joint name="arm_gripper_joint" type="fixed">-->
<!--    <parent link="ee_link"/>-->
<!--    <child link="robotiq_140_robotiq_arg2f_base_link"/>-->
<!--    <origin rpy="-1.57 1.57 -1.57" xyz="0.0 0.0 0.0"/>-->
<!--  </joint>-->

  <!-- connect arm to world -->
  <!-- <joint name="world_arm_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin rpy="0.0 0.0 0" xyz="0 0 0"/>
  </joint> -->
```

Now, the robot base can move.

![image](https://user-images.githubusercontent.com/20351686/167341025-b0eefd4f-a468-484c-be59-6d26a4d57724.png)

enjoy

**Comment by Anchoret13** [comment]
Thanks for your help! Problem solved!
