### ISSUE TITLE
Robot not working properly after shifting the target end-effector position out of given range

### ISSUE THREAD

**Issue by sachin-ag** [ElectronicElephant/pybullet_ur5_robotiq#8]
When I shifted the target position of end-effector out of the range given in the side panel (-0.224 to 0.224 for x and y), the arm is not able to reach those points. Do you have an idea why this is happening?

**Comment by ElectronicElephant** [comment]
Can you provide more details please?

**Comment by sachin-ag** [comment]
In the user debug panel, one can set range of 'x' and 'y' from -0224 to 0.224. However, when I tried to move the centre of the robot to (0,0,0) (as I do not need the box for my experiment), the robot was not able to reach any of the points set using debug panel.

**Comment by ElectronicElephant** [comment]
I don't quite understand your situation. Please show me the code. 🤔

**Comment by sachin-ag** [comment]
I have changed:

`env = ClutteredPushGrasp(UR5Robotiq85((0, 0.5, 0), (0, 0, 0)))`

to:

`env = ClutteredPushGrasp(UR5Robotiq85((0, 0, 0), (0, 0, 0)))`

**Comment by ElectronicElephant** [comment]
Hi,

The robot is collided with the box. You need to move away the box in the `Env` class.
