### ISSUE TITLE
How to put the rgbd camera on the robot end effector

### ISSUE THREAD

**Issue by Pingcheng-Jian** [ElectronicElephant/pybullet_ur5_robotiq#9]
Hi. Could you please let me know how to put camera on the end effector of the Ur5 robot arm?

**Comment by ElectronicElephant** [comment]
Hi, I'm glad that you are interested in this project. Actually, there is no such `Camera` class in PyBullet. Instead, one just calculate the camera matrix and call `p.getCameraImage`. Therefore, you can simply get the position of the end effector, calculate the matrix, and finally take the picture.

**Comment by Pingcheng-Jian** [comment]
Hi, thanks a lot for your instruction. I am working on calculating the camera matrix according to the position of the end effector.
